# -*- coding: utf-8 -*-
"""EDA_Tech_Store

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gw5XBYb8dSLfP49ffg6Jg_yp9c70-wMo
"""

import pandas as pd

df_vendas = pd.read_csv('/content/vendas.csv')
df_vendas.head()

df_vendas['receita_total'] = df_vendas['quantidade'] * df_vendas['preco_unitario']
df_vendas.head()

import sqlite3

conn = sqlite3.connect(":memory:")
df_vendas.to_sql("vendas", conn, index=False, if_exists="replace")

filtra_produto_eletronicos = pd.read_sql_query("SELECT * FROM vendas WHERE categoria = 'Eletrônicos'", conn)
filtra_produto_eletronicos

produto_mais_vendido = pd.read_sql_query("SELECT produto, categoria, SUM(quantidade) AS total_vendido FROM vendas GROUP BY produto ORDER BY total_vendido DESC LIMIT 1", conn)
produto_mais_vendido

regiao_maior_receita = pd.read_sql_query("SELECT regiao, SUM(receita_total) FROM vendas GROUP BY regiao ORDER BY receita_total DESC LIMIT 1", conn)
regiao_maior_receita